"""On-demand fetch of large data products from Zenodo (via :mod:`pooch`).

The small inputs needed to *import and run* the package live in
``hod_mod/data/`` and are shipped with the wheel (see ``package-data`` in
``pyproject.toml``).  Everything that is too big to track in git is deposited
on a Zenodo **data record** and pulled on demand here, with SHA256
verification.  Two categories go through this layer:

* **Tier 2 — large external inputs** that scripts used to read from hard-coded
  home paths: the LSDR10 GALxEVT cross-correlation measurements and the
  eROSITA CALDB PSF/response files.
* **Tier 3 — curated benchmark results**: the final posterior chains
  (``flatchain.npz`` / ``chain.h5``) and headline figures.  The 60k+
  intermediate ``.npz`` are *not* archived — they are regenerable from the
  chains + a committed config (see ``hod_mod/scripts/``).

Resolution order for :func:`fetch`
----------------------------------
1. ``$HOD_MOD_DATA_DIR/<name>`` — if that env var points at a local mirror that
   already contains the file, it is returned directly with **no download**
   (lets an existing ``~/data`` tree keep working unchanged).
2. The pooch cache (``$HOD_MOD_DATA_CACHE`` or the OS cache dir), downloading
   from Zenodo on first use and verifying the SHA256 listed in ``registry.txt``.

Configuration (environment variables)
-------------------------------------
* ``HOD_MOD_DATA_DOI``     — Zenodo DOI of the data record.  Use the *concept*
  DOI to always track the latest version, or a *version* DOI to pin a snapshot
  for reproducibility.  Overrides :data:`DEFAULT_DATA_DOI`.
* ``HOD_MOD_DATA_BASEURL`` — override the base URL entirely (e.g. a ``file://``
  mirror for offline use, or a non-Zenodo object store).  Takes precedence over
  the DOI.
* ``HOD_MOD_DATA_DIR``     — local mirror checked *before* any download.
* ``HOD_MOD_DATA_CACHE``   — override the pooch cache directory.

Examples
--------
Fetch a curated benchmark chain (downloads + checksums on first call, cache hit
afterwards)::

    from hod_mod.data_io.registry import fetch
    path = fetch("results/benchmarks/more2015_logM11_12/flatchain.npz")

Pin a specific Zenodo version for a reproducible run::

    HOD_MOD_DATA_DOI=10.5281/zenodo.1234567 python my_script.py
"""

from __future__ import annotations

import os
from pathlib import Path

import pooch

# Zenodo data-record DOI.  This is the version DOI of the first deposit; switch
# to the concept DOI to always track the latest version, or override at runtime
# with ``$HOD_MOD_DATA_DOI``.
DEFAULT_DATA_DOI = "10.5281/zenodo.21079850"

# Sentinel DOI used before any record is published; :func:`fetch` refuses to
# download while this is the active DOI.
PLACEHOLDER_DOI = "10.5281/zenodo.0000000"

# ``filename  sha256`` registry shipped with the package; generated by
# ``hod_mod/scripts/data/make_data_registry.py`` and refreshed after each
# Zenodo upload.
REGISTRY_FILE = Path(__file__).with_name("registry.txt")


def zenodo_key(name: str) -> str:
    """Map a logical data path to its flat Zenodo filename.

    Zenodo's file API does not allow ``/`` in filenames, so nested paths are
    flattened by replacing the separator with ``__`` (no archived path contains
    ``__``, so this round-trips unambiguously). Already-flat names — like the
    ``S1_mcmc_summary.json`` seed — pass through unchanged.
    """
    return name.replace("/", "__")


def _data_doi() -> str:
    return os.environ.get("HOD_MOD_DATA_DOI", DEFAULT_DATA_DOI)


def _base_url() -> str:
    explicit = os.environ.get("HOD_MOD_DATA_BASEURL")
    if explicit:
        return explicit if explicit.endswith("/") else explicit + "/"
    return f"doi:{_data_doi()}/"


def _get_pooch() -> pooch.Pooch:
    """Build a :class:`pooch.Pooch` from the current env + shipped registry.

    Rebuilt on each call (cheap) so that env-var changes — DOI, cache dir,
    base URL — are picked up without reimporting.
    """
    p = pooch.create(
        path=pooch.os_cache("hod_mod"),
        base_url=_base_url(),
        registry=None,
        env="HOD_MOD_DATA_CACHE",
    )
    if REGISTRY_FILE.exists():
        p.load_registry(REGISTRY_FILE)
    return p


def list_registry() -> dict[str, str]:
    """Return the ``{zenodo_key: hash}`` registry currently shipped."""
    return dict(_get_pooch().registry)


def fetch(name: str, *, progressbar: bool = True) -> Path:
    """Return a local path to data product *name*, downloading if needed.

    Parameters
    ----------
    name : str
        Logical data path (e.g.
        ``"results/benchmarks/more2015_logM11_12/flatchain.npz"``). It is
        flattened to its Zenodo filename via :func:`zenodo_key` internally.
    progressbar : bool, default True
        Show a download progress bar (ignored on a cache hit / local mirror).

    Returns
    -------
    pathlib.Path
        Path to the verified local file.

    Raises
    ------
    KeyError
        *name* is not in ``registry.txt``.
    RuntimeError
        The Zenodo DOI is still the unpublished placeholder and no local
        mirror / base-URL override was provided.
    """
    # 1. Local mirror — return directly, no network, no checksum.
    mirror = os.environ.get("HOD_MOD_DATA_DIR")
    if mirror:
        local = Path(mirror).expanduser() / name
        if local.exists():
            return local

    pup = _get_pooch()
    zkey = zenodo_key(name)
    if zkey not in pup.registry:
        raise KeyError(
            f"{name!r} (Zenodo key {zkey!r}) is not in the data registry "
            f"({REGISTRY_FILE}). Regenerate it with "
            "hod_mod/scripts/data/make_data_registry.py, or set "
            "$HOD_MOD_DATA_DIR to a local mirror that contains the file."
        )

    using_override = bool(os.environ.get("HOD_MOD_DATA_BASEURL"))
    if not using_override and _data_doi() == PLACEHOLDER_DOI:
        raise RuntimeError(
            f"{name!r} must be downloaded but the Zenodo data DOI is unset "
            f"(still the {PLACEHOLDER_DOI} placeholder). Set $HOD_MOD_DATA_DOI "
            "to the published record DOI, point $HOD_MOD_DATA_DIR at a local "
            "mirror, or set $HOD_MOD_DATA_BASEURL to an alternate host."
        )

    return Path(pup.fetch(zkey, progressbar=progressbar))
