"""Tests for hod_mod.observables.lensing (Σ_crit, mis-centering, 2-halo,
strong lensing, ClusterLensingPrediction).

Σ_crit goldens generated by make_lensing_goldens.py against the reference
halo_lensing implementation on colossus planck18 (h=0.6766, Ωm=0.3111).
"""

import numpy as np
import pytest
import jax
import jax.numpy as jnp

from hod_mod.core.power_spectrum import eisenstein_hu_pk_phys
from hod_mod.core.halo_mass_function import make_hmf
from hod_mod.core.halo_profiles import nfw_sigma
from hod_mod.core.lensing_profiles import hernquist_mean_sigma
from hod_mod.observables.lensing import (
    sigma_crit, inv_sigma_crit,
    offset_sigma, offset_sigma_gaussian, mean_sigma_from_tab,
    sigma_2h, delta_sigma_2h,
    solve_einstein_radius, radial_critical_radius, magnification,
    tangential_shear,
    ClusterLensingPrediction,
)

enable_x64 = jax.enable_x64

# colossus planck18 (the goldens' cosmology)
THETA = {
    "h": 0.6766, "Omega_m": 0.3111, "Omega_b": 0.0490,
    "n_s": 0.9665, "sigma8": 0.8102, "ln10^{10}A_s": 3.044,
    "w0": -1.0, "wa": 0.0,
}

SC_ZL = np.array([0.2, 0.3, 0.5])
SC_ZS = np.array([0.8, 1.0, 2.0, 3.0])
SIGMA_CRIT_COMOVING = np.array([
    [3.439727892186e+15, 3.230490415753e+15, 2.886692969732e+15,
     2.789777382043e+15],
    [2.689937997733e+15, 2.407813637191e+15, 1.997612992865e+15,
     1.892375456956e+15],
    [2.620060688590e+15, 1.972479514177e+15, 1.329239783715e+15,
     1.201354270173e+15]])


@pytest.fixture(scope="module")
def hmf_eh():
    return make_hmf("tinker08",
                    pk_func=lambda k, z, th: eisenstein_hu_pk_phys(k, th))


@pytest.fixture(scope="module")
def clp(hmf_eh):
    return ClusterLensingPrediction(profile="bmo", mdef="vir",
                                    cm_relation="duffy08", tau_v=2.5,
                                    hmf=hmf_eh)


class TestSigmaCrit:
    def test_goldens(self):
        with enable_x64():
            for i, zl in enumerate(SC_ZL):
                sc = np.asarray(sigma_crit(zl, jnp.asarray(SC_ZS), THETA,
                                           comoving=True))
                np.testing.assert_allclose(sc, SIGMA_CRIT_COMOVING[i],
                                           rtol=5e-4)

    def test_comoving_physical_ratio(self):
        zl = 0.4
        sc_c = float(sigma_crit(zl, 1.5, THETA, comoving=True))
        sc_p = float(sigma_crit(zl, 1.5, THETA, comoving=False))
        np.testing.assert_allclose(sc_p / sc_c, (1.0 + zl) ** 2, rtol=1e-6)

    def test_unlensed_source(self):
        assert float(inv_sigma_crit(0.5, 0.3, THETA)) == 0.0
        assert float(inv_sigma_crit(0.5, 0.5, THETA)) == 0.0
        assert np.isinf(float(sigma_crit(0.5, 0.3, THETA)))

    def test_monotone_decreasing_in_zs(self):
        zs = jnp.array([0.6, 1.0, 2.0, 4.0])
        sc = np.asarray(sigma_crit(0.4, zs, THETA))
        assert np.all(np.diff(sc) < 0)


class TestOffCentering:
    rho_s, r_s = 1.45e15, 0.171

    def _sig_fn(self):
        return lambda r: nfw_sigma(r, self.rho_s, self.r_s)

    def test_small_radius_limit(self):
        # R << R_off: Σ_off(R) → Σ(R_off)
        sig = self._sig_fn()
        s0 = float(offset_sigma(jnp.array([1e-5]), 0.4, sig)[0])
        np.testing.assert_allclose(s0, float(sig(jnp.array([0.4]))[0]),
                                   rtol=1e-4)

    def test_zero_offset_limit(self):
        sig = self._sig_fn()
        R = jnp.array([0.3, 1.0, 3.0])
        s = np.asarray(offset_sigma_gaussian(R, 1e-5, sig))
        np.testing.assert_allclose(s, np.asarray(sig(R)), rtol=1e-4)

    def test_against_dense_trapezoid(self):
        # independent azimuthal integration on a dense trapezoid grid
        with enable_x64():
            sig = self._sig_fn()
            r_off = 0.35
            phi = np.linspace(0.0, np.pi, 8193)
            for R in (0.05, 0.34, 0.36, 1.0, 5.0):
                r_ev = np.sqrt(R**2 + r_off**2 + 2 * R * r_off * np.cos(phi))
                ref = np.trapezoid(np.asarray(sig(jnp.asarray(r_ev))),
                                   phi) / np.pi
                ours = float(offset_sigma(jnp.array([R]), r_off, sig)[0])
                # R ≈ R_off has the integrable log feature — looser there
                rtol = 5e-3 if abs(R - r_off) < 0.05 else 2e-4
                np.testing.assert_allclose(ours, ref, rtol=rtol)

    def test_mean_sigma_from_tab(self):
        # against the analytic NFW Σ̄ (closure term slightly under-counts
        # the log-divergent core — inner grid point at 1e-3 keeps it ~0.1%)
        from hod_mod.core.halo_profiles import nfw_mean_sigma
        with enable_x64():
            R_tab = jnp.logspace(-3, 2, 256)
            sig_tab = nfw_sigma(R_tab, self.rho_s, self.r_s)
            R = jnp.array([0.05, 0.3, 1.0, 10.0])
            ours = np.asarray(mean_sigma_from_tab(R, R_tab, sig_tab))
            exact = np.asarray(nfw_mean_sigma(R, self.rho_s, self.r_s))
            np.testing.assert_allclose(ours, exact, rtol=3e-3)


class TestTwoHalo:
    def test_bias_scaling(self, hmf_eh):
        # ΔΣ_2h / b(M) must be independent of M
        R = jnp.array([2.0, 8.0])
        d13 = np.asarray(delta_sigma_2h(R, 1e13, 0.3, THETA, hmf_eh))
        d15 = np.asarray(delta_sigma_2h(R, 1e15, 0.3, THETA, hmf_eh))
        b13 = float(hmf_eh.bias(jnp.array([1e13]), 0.3, THETA)[0])
        b15 = float(hmf_eh.bias(jnp.array([1e15]), 0.3, THETA)[0])
        np.testing.assert_allclose(d13 / b13, d15 / b15, rtol=1e-6)

    def test_against_dense_brute_force(self, hmf_eh):
        # independent numpy pipeline: dense trapezoid ξ(r) + LOS integral
        with enable_x64():
            from hod_mod.observables.lensing import _pk_lin_tab
            from hod_mod.core.halo_mass_function import growth_factor
            log_k, log_pk = _pk_lin_tab(THETA)
            k = np.exp(np.asarray(log_k))
            pk = np.exp(np.asarray(log_pk))
            kk = np.logspace(-4, 3, 60000)
            pkk = np.interp(kk, k, pk)
            z, m = 0.3, 1e14
            growth = float(growth_factor(z, THETA))
            b = float(hmf_eh.bias(jnp.array([m]), z, THETA)[0])
            rho_m = THETA["Omega_m"] * 2.775e11
            for R in (1.0, 5.0):
                chi = np.linspace(0.0, 300.0, 60000)
                r = np.sqrt(R**2 + chi**2)
                xi = np.array([
                    np.trapezoid(kk**2 * pkk * np.sinc(kk * ri / np.pi), kk)
                    / (2 * np.pi**2) for ri in r[::200]])
                wp = 2.0 * np.trapezoid(xi, chi[::200])
                ref = rho_m * b * growth**2 * wp
                ours = float(sigma_2h(jnp.array([R]), m, z, THETA, hmf_eh)[0])
                np.testing.assert_allclose(ours, ref, rtol=0.03)


class TestStrongLensing:
    M, ZL, ZS = 1e15, 0.3, 2.0

    def test_einstein_ring_consistency(self, clp):
        with enable_x64():
            r_e, theta_e = clp.einstein_radius(self.M, self.ZL, self.ZS, THETA)
            _, kbar = clp._kappa_fns(self.M, self.ZL, self.ZS, THETA)
            np.testing.assert_allclose(float(kbar(r_e)), 1.0, atol=1e-8)
            assert 1.0 < float(theta_e) < 60.0   # arcsec, massive cluster

    def test_point_mass_limit(self):
        # tiny-r_b Hernquist → point mass: π R_E² Σ_crit = M
        with enable_x64():
            M_pt, r_b = 1e14, 1e-6
            isc = float(inv_sigma_crit(self.ZL, self.ZS, THETA))
            kbar = lambda r: jnp.squeeze(
                hernquist_mean_sigma(jnp.atleast_1d(r), M_pt, r_b)) * isc
            r_e = float(solve_einstein_radius(kbar))
            r_e_ana = np.sqrt(M_pt * isc / np.pi)
            np.testing.assert_allclose(r_e, r_e_ana, rtol=1e-4)

    def test_theta_e_monotone_in_mass(self, clp):
        with enable_x64():
            te = [float(clp.einstein_radius(m, self.ZL, self.ZS, THETA)[1])
                  for m in (3e14, 1e15, 3e15)]
            assert te[0] < te[1] < te[2]

    def test_subcritical_nan(self, clp):
        r_e, _ = clp.einstein_radius(1e11, 0.3, 0.5, THETA)
        assert bool(jnp.isnan(r_e))

    def test_magnification_sign_flips(self, clp):
        with enable_x64():
            r_t, r_r = clp.critical_curves(self.M, self.ZL, self.ZS, THETA)
            assert 0.0 < float(r_r) < float(r_t)
            eps = 1.02
            mu = np.asarray(clp.magnification(
                jnp.array([float(r_r) / eps, float(r_r) * eps,
                           float(r_t) / eps, float(r_t) * eps]),
                self.M, self.ZL, self.ZS, THETA))
            assert mu[0] > 0 and mu[1] < 0       # radial curve flip
            assert mu[2] < 0 and mu[3] > 0       # tangential curve flip
            assert np.all(np.abs(mu) > 5)        # diverging near both

    def test_radial_critical_definition(self, clp):
        with enable_x64():
            kap, kbar = clp._kappa_fns(self.M, self.ZL, self.ZS, THETA)
            r_r = radial_critical_radius(kap, kbar)
            d = 1.0 + float(kbar(r_r)) - 2.0 * float(kap(r_r))
            np.testing.assert_allclose(d, 0.0, atol=1e-8)

    def test_gamma_t_identity(self, clp):
        R = jnp.array([0.05, 0.2, 1.0])
        kap = clp.kappa(R, self.M, self.ZL, self.ZS, THETA)
        kbar = clp.mean_kappa(R, self.M, self.ZL, self.ZS, THETA)
        gt = tangential_shear(kap, kbar)
        ds = clp.delta_sigma_1h(R, self.M, self.ZL, THETA)
        isc = float(inv_sigma_crit(self.ZL, self.ZS, THETA))
        np.testing.assert_allclose(np.asarray(gt), np.asarray(ds) * isc,
                                   rtol=1e-5)

    def test_theta_e_gradient_vs_fd(self, clp):
        with enable_x64():
            f = lambda lm: clp.einstein_radius(10.0**lm, self.ZL, self.ZS,
                                               THETA)[1]
            g = float(jax.grad(f)(15.0))
            fd = float((f(15.0 + 5e-4) - f(15.0 - 5e-4)) / 1e-3)
            np.testing.assert_allclose(g, fd, rtol=1e-3)

    def test_composite_lens(self, clp):
        # Hernquist stars + halo: composite θ_E exceeds the halo-only θ_E
        with enable_x64():
            _, kbar_halo = clp._kappa_fns(3e13, self.ZL, self.ZS, THETA)
            isc = float(inv_sigma_crit(self.ZL, self.ZS, THETA))
            kbar_star = lambda r: jnp.squeeze(
                hernquist_mean_sigma(jnp.atleast_1d(r), 2e11, 0.003)) * isc
            r_half = solve_einstein_radius(kbar_halo)
            r_comp = solve_einstein_radius(
                lambda r: kbar_halo(r) + kbar_star(r))
            assert bool(jnp.isnan(r_half)) or float(r_comp) > float(r_half)
            assert bool(jnp.isfinite(r_comp))


class TestClusterLensingPrediction:
    def test_profiles_agree_inside(self, hmf_eh):
        # NFW / TJ / BMO must agree at R << r_t
        R = jnp.array([0.02, 0.05])
        preds = {p: ClusterLensingPrediction(profile=p, mdef="vir",
                                             cm_relation="duffy08",
                                             hmf=hmf_eh)
                 for p in ("nfw", "tnfw", "bmo")}
        sig = {p: np.asarray(c.sigma_1h(R, 1e14, 0.3, THETA))
               for p, c in preds.items()}
        np.testing.assert_allclose(sig["tnfw"], sig["nfw"], rtol=0.05)
        np.testing.assert_allclose(sig["bmo"], sig["nfw"], rtol=0.05)
        # ordering at truncation-sensitive radii: NFW ≥ BMO ≥ TJ
        R_out = jnp.array([3.0])
        s_out = {p: float(c.sigma_1h(R_out, 1e14, 0.3, THETA)[0])
                 for p, c in preds.items()}
        assert s_out["nfw"] > s_out["bmo"] > s_out["tnfw"]

    def test_delta_sigma_total_composition(self, clp):
        with enable_x64():
            R = jnp.array([0.1, 1.0, 10.0])
            f_cen, s_off = 0.7, 0.4
            tot = np.asarray(clp.delta_sigma_total(R, 1e14, 0.3, THETA,
                                                   f_cen=f_cen,
                                                   sigma_off=s_off))
            parts = (f_cen * np.asarray(clp.delta_sigma_1h(R, 1e14, 0.3, THETA))
                     + (1 - f_cen) * np.asarray(
                         clp.delta_sigma_off(R, 1e14, 0.3, THETA,
                                             sigma_off=s_off))
                     + np.asarray(clp.delta_sigma_2h(R, 1e14, 0.3, THETA)))
            np.testing.assert_allclose(tot, parts, rtol=1e-6)

    def test_sigma_off_requires_one_kwarg(self, clp):
        with pytest.raises(ValueError):
            clp.sigma_off(jnp.array([1.0]), 1e14, 0.3, THETA)
        with pytest.raises(ValueError):
            clp.sigma_off(jnp.array([1.0]), 1e14, 0.3, THETA,
                          r_off=0.1, sigma_off=0.1)

    def test_gamma_t_positive_and_finite(self, clp):
        gt = clp.gamma_t(jnp.logspace(-1, 1, 12), 1e14, 0.3, 1.0, THETA,
                         f_cen=0.7, sigma_off=0.3)
        assert bool(jnp.all(jnp.isfinite(gt)))
        assert bool(jnp.all(gt > 0))

    def test_unknown_profile_raises(self):
        with pytest.raises(ValueError):
            ClusterLensingPrediction(profile="einasto")
