"""Tests for hod_mod.core.lensing_profiles (TJ / BMO / Hernquist kernels).

Golden values generated by::

    python hod_mod/scripts/cosmology/make_lensing_goldens.py \
        --halo-lensing-path <clone of github.com/massarin/halo_lensing>

against the reference implementation (Oguri et al. 2026, arXiv:2512.13954)
with mpmath (dps=50) for the P/Q hyperbolic combinations and the BMO Fourier
window.  Note the deliberate normalization difference for the sharply
truncated profile: hod_mod Σ_TJ = 4 ρ_s r_s f(x, c) is the exact projection
of the truncated density (the reference's real-space tj_* carry an extra
m_nfw(c)); the *dimensionless kernels* compared here are identical.
"""

import numpy as np
import pytest
import jax
import jax.numpy as jnp

enable_x64 = jax.enable_x64

from hod_mod.core.halo_profiles import (
    HaloProfile, nfw_sigma, nfw_delta_sigma, nfw_uk_jax, mdef_delta_rho,
)
from hod_mod.core.lensing_profiles import (
    _tj_sigma_dl, _tj_bsigma_dl, _bmo_sigma_dl, _bmo_bsigma_dl,
    _m_bmo_dl, _m_bmo_tot_dl, _hern_sigma_dl, _hern_bsigma_dl,
    _pq_hyperbolic, _m_nfw,
    tnfw_rho, tnfw_mass, tnfw_sigma, tnfw_mean_sigma, tnfw_delta_sigma,
    tnfw_uk,
    bmo_rho, bmo_mass, bmo_mass_total, bmo_sigma, bmo_mean_sigma,
    bmo_delta_sigma, bmo_uk_jax,
    hernquist_rho, hernquist_mass, hernquist_sigma, hernquist_mean_sigma,
    hernquist_delta_sigma,
    nfw_params_from_mass,
)

# --------------------------------------------------------------------------
# Goldens (make_lensing_goldens.py, 2026-07-07)
# --------------------------------------------------------------------------

GOLD_X = np.array([1e-3, 0.01, 0.1, 0.3, 0.5, 0.9, 0.985, 1.0, 1.015, 1.5,
                   2.0, 2.9, 3.0, 5.0, 6.0, 8.0, 15.0, 40.0])

TJ_SIGMA_C6 = np.array([
    3.294809536932e+00, 2.143846827163e+00, 1.008646870411e+00,
    5.241835493106e-01, 3.414717910999e-01, 1.830193624054e-01,
    1.640252418298e-01, 1.609817628054e-01, 1.580218502065e-01,
    9.335602291866e-02, 6.009398881450e-02, 3.126045449931e-02,
    2.926470271617e-02, 7.817903334029e-03, 0.0, 0.0, 0.0, 0.0])
TJ_BSIGMA_C6 = np.array([
    3.544807094149e+00, 2.393688739437e+00, 1.251340673515e+00,
    7.407666719647e-01, 5.319390450833e-01, 3.316183052840e-01,
    3.054434330101e-01, 3.011870710810e-01, 2.970299650338e-01,
    2.007956316612e-01, 1.454250640675e-01, 9.159873462846e-02,
    8.757656993834e-02, 4.155010044492e-02, 3.024353588646e-02,
    1.701198893613e-02, 4.838965741833e-03, 6.804795574453e-04])
TJ_SIGMA_C3 = np.array([
    3.281615268745e+00, 2.130652514806e+00, 9.954481384832e-01,
    5.109489189769e-01, 3.281643603572e-01, 1.694459675889e-01,
    1.503723428516e-01, 1.473139127472e-01, 1.443387655249e-01,
    7.900434847303e-02, 4.454116128743e-02, 8.464774376717e-03,
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
TJ_BSIGMA_C3 = np.array([
    3.531612825580e+00, 2.380494449390e+00, 1.238144174106e+00,
    7.275522576820e-01, 5.186884685683e-01, 3.182375165453e-01,
    2.920242940320e-01, 2.877607494539e-01, 2.835963340485e-01,
    1.870505327507e-01, 1.311644330065e-01, 7.527225513313e-02,
    7.069937345777e-02, 2.545177444480e-02, 1.767484336444e-02,
    9.942099392498e-03, 2.827974938311e-03, 3.976839756999e-04])
TJ_SIGMA_C15 = np.array([
    3.299437044884e+00, 2.148474338729e+00, 1.013274743378e+00,
    5.288143463686e-01, 3.461084560767e-01, 1.876767752440e-01,
    1.686886520438e-01, 1.656462905603e-01, 1.626875133684e-01,
    9.806834712173e-02, 6.487628272394e-02, 3.623734255999e-02,
    3.426990054357e-02, 1.396094107200e-02, 9.834141551841e-03,
    5.388389200077e-03, 0.0, 0.0])
TJ_BSIGMA_C15 = np.array([
    3.549434601329e+00, 2.398316249171e+00, 1.255968363949e+00,
    7.453958237606e-01, 5.365711261736e-01, 3.362607086030e-01,
    3.100888098642e-01, 3.058330015134e-01, 3.016764577321e-01,
    2.054650901707e-01, 1.501284470949e-01, 9.639328105246e-02,
    9.238399456320e-02, 4.679933318843e-02, 3.606570728464e-02,
    2.344758519185e-02, 8.155949876621e-03, 1.146930451400e-03])

BMO_SIGMA_T12P5 = np.array([
    3.290684273116e+00, 2.139720375669e+00, 1.004473113216e+00,
    5.198857740404e-01, 3.371179273512e-01, 1.787571994826e-01,
    1.598090529715e-01, 1.567744407107e-01, 1.538236086839e-01,
    8.954265581717e-02, 5.679732152689e-02, 2.904178315105e-02,
    2.717343830890e-02, 8.720583394866e-03, 5.393589179465e-03,
    2.278459836560e-03, 2.036083413480e-04, 1.294308896494e-06])
BMO_BSIGMA_T12P5 = np.array([
    3.540681827996e+00, 2.389562851565e+00, 1.247187386985e+00,
    7.365274716444e-01, 5.276387574229e-01, 3.273023187703e-01,
    3.011400855294e-01, 2.968864505485e-01, 2.927322147318e-01,
    1.966558191640e-01, 1.415433607786e-01, 8.831775937151e-02,
    8.436942703138e-02, 4.003173967484e-02, 2.989303158935e-02,
    1.835012556812e-02, 5.733613231222e-03, 8.252528140823e-04])
BMO_MASS_T12P5 = np.array([
    4.993340792290e-07, 4.934072266381e-05, 4.400814371764e-03,
    3.157810156420e-02, 7.202873880662e-02, 1.674451424653e-01,
    1.884332319804e-01, 1.921363216029e-01, 1.958380001281e-01,
    3.128302715748e-01, 4.240713888500e-01, 5.960537312598e-01,
    6.130189270042e-01, 8.788504750385e-01, 9.704492840128e-01,
    1.098491537635e+00, 1.268244290930e+00, 1.319482637492e+00])
BMO_MTOT = {3.0: 4.666245937027e-01, 12.5: 1.321506350004e+00,
            25.0: 1.881177422384e+00}

HERN_SIGMA = np.array([
    1.220184402463e+01, 7.599164212779e+00, 3.108547414762e+00,
    1.334840544858e+00, 7.494346370742e-01, 3.182989330708e-01,
    2.736456268127e-01, 2.666666666667e-01, 2.599277560254e-01,
    1.261871525952e-01, 6.973319205205e-02, 3.024546903357e-02,
    2.792669738311e-02, 7.894890607610e-03, 4.909345013478e-03,
    2.272458110462e-03, 3.948600444699e-04, 2.304770461600e-05])
HERN_BSIGMA = np.array([
    1.320182522188e+01, 8.597974397638e+00, 4.057176060313e+00,
    2.119334828536e+00, 1.388511980272e+00, 7.547877560736e-01,
    6.788359794550e-01, 6.666666666667e-01, 6.548316930750e-01,
    3.963604984734e-01, 2.636001412813e-01, 1.490645676198e-01,
    1.411975310791e-01, 6.003871299388e-02, 4.358804865938e-02,
    2.596470118306e-02, 8.031289427654e-03, 1.202430362446e-03])

PQ_X = np.array([1e-3, 0.1, 0.5, 2.0, 13.9, 14.1, 29.0, 31.0, 50.0, 300.0])
P_GOLD = np.array([
    -7.330540974726e-03, -2.731303940804e-01, -5.992044655175e-01,
    -5.159056633391e-01, -7.274432043866e-02, -7.168828782891e-02,
    -3.456597777625e-02, -3.232606505438e-02, -2.001607774303e-02,
    -3.333407417287e-03])
Q_GOLD = np.array([
    -6.330543529351e+00, -1.741512150628e+00, -3.237061669662e-01,
    1.545770464509e-01, 5.359146373881e-03, 5.202365373509e-03,
    1.197756653694e-03, 1.047221225120e-03, 4.009678129146e-04,
    1.111185201654e-05])

BMO_UK_K = np.logspace(-3, 2.5, 23)
BMO_UK_T15P0 = np.array([
    9.999891592506e-01, 9.999657273554e-01, 9.998916971974e-01,
    9.996581715463e-01, 9.989244696731e-01, 9.966420282025e-01,
    9.897046990854e-01, 9.696641497749e-01, 9.173949399791e-01,
    8.040491980104e-01, 6.197049661077e-01, 4.095911545154e-01,
    2.342650819837e-01, 1.161990466646e-01, 4.990326656776e-02,
    1.884972746317e-02, 6.492675541172e-03, 2.124903034211e-03,
    6.801546710380e-04, 2.159465179716e-04, 6.837605905423e-05,
    2.163123514727e-05, 6.841281420968e-06])

# |x−1| ≤ 0.01 is the TJ quadratic-interpolation window (~1e-4 accurate);
# everything else is the closed form.
_TJ_WINDOW = np.abs(GOLD_X - 1.0) <= 0.01


# --------------------------------------------------------------------------


class TestPQHyperbolic:
    def test_goldens_x64(self):
        with enable_x64():
            p, q = _pq_hyperbolic(jnp.asarray(PQ_X))
            np.testing.assert_allclose(np.asarray(p), P_GOLD, rtol=1e-6)
            np.testing.assert_allclose(np.asarray(q), Q_GOLD, rtol=1e-6)

    def test_asymptotic_seam_continuity(self):
        with enable_x64():
            below = _pq_hyperbolic(jnp.array([30.0 - 1e-9]))
            above = _pq_hyperbolic(jnp.array([30.0 + 1e-9]))
            for b, a in zip(below, above):
                np.testing.assert_allclose(np.asarray(b), np.asarray(a),
                                           rtol=1e-6)

    def test_float32_reasonable(self):
        p, q = _pq_hyperbolic(jnp.asarray(PQ_X, dtype=jnp.float32))
        np.testing.assert_allclose(np.asarray(p), P_GOLD, rtol=5e-4)
        np.testing.assert_allclose(np.asarray(q), Q_GOLD, rtol=5e-4)

    def test_grad_finite(self):
        g = jax.vmap(jax.grad(lambda x: _pq_hyperbolic(x)[0]))(jnp.asarray(PQ_X))
        assert bool(jnp.all(jnp.isfinite(g)))


class TestTNFW:
    @pytest.mark.parametrize("c,sig_gold,bsig_gold", [
        (3.0, TJ_SIGMA_C3, TJ_BSIGMA_C3),
        (6.0, TJ_SIGMA_C6, TJ_BSIGMA_C6),
        (15.0, TJ_SIGMA_C15, TJ_BSIGMA_C15),
    ])
    def test_kernel_goldens(self, c, sig_gold, bsig_gold):
        with enable_x64():
            f = np.asarray(_tj_sigma_dl(jnp.asarray(GOLD_X), c))
            g = np.asarray(_tj_bsigma_dl(jnp.asarray(GOLD_X), c))
        rtol = np.where(_TJ_WINDOW, 5e-4, 1e-8)
        assert np.all(np.abs(f - sig_gold) <= rtol * np.abs(sig_gold) + 1e-12)
        assert np.all(np.abs(g - bsig_gold) <= rtol * np.abs(bsig_gold))

    def test_sigma_zero_beyond_truncation(self):
        s = tnfw_sigma(jnp.array([6.0, 7.0, 50.0]), 1e15, 1.0, 6.0)
        np.testing.assert_array_equal(np.asarray(s), 0.0)

    def test_2d_mass_conservation(self):
        # π R² Σ̄ → M_trunc = 4π ρ_s r_s³ m_nfw(c) for R ≥ c r_s
        rho_s, r_s, c = 1.4e15, 0.2, 6.0
        R = jnp.array([1.2001, 5.0, 80.0])
        m2d = np.pi * np.asarray(R)**2 * np.asarray(
            tnfw_mean_sigma(R, rho_s, r_s, c))
        m_t = 4.0 * np.pi * rho_s * r_s**3 * float(_m_nfw(jnp.asarray(c)))
        np.testing.assert_allclose(m2d, m_t, rtol=1e-5)
        np.testing.assert_allclose(
            float(tnfw_mass(jnp.array([100.0]), rho_s, r_s, c)[0]),
            m_t, rtol=1e-6)

    def test_delta_sigma_identity(self):
        R = jnp.logspace(-2, 1, 40)
        ds = tnfw_delta_sigma(R, 1.4e15, 0.2, 6.0)
        expect = (tnfw_mean_sigma(R, 1.4e15, 0.2, 6.0)
                  - tnfw_sigma(R, 1.4e15, 0.2, 6.0))
        np.testing.assert_allclose(np.asarray(ds), np.asarray(expect),
                                   rtol=1e-6)

    def test_nfw_limit_inside_truncation(self):
        # deep inside a very extended truncation the projection is NFW-like
        R = jnp.logspace(-2, -0.5, 10)
        s_t = np.asarray(tnfw_sigma(R, 1.4e15, 0.2, 100.0))
        s_n = np.asarray(nfw_sigma(R, 1.4e15, 0.2))
        np.testing.assert_allclose(s_t, s_n, rtol=1e-2)

    def test_abel_projection(self):
        # analytic Σ vs numerical LOS integration of the truncated density
        from scipy.integrate import quad
        with enable_x64():
            rho_s, r_s, c = 1.4e15, 0.2, 6.0
            for R in (0.05, 0.3, 1.0):
                zmax = np.sqrt((c * r_s)**2 - R**2)
                num = 2.0 * quad(
                    lambda zz: float(tnfw_rho(
                        jnp.array([np.sqrt(R**2 + zz**2)]), rho_s, r_s, c)[0]),
                    0.0, zmax, limit=200)[0]
                ana = float(tnfw_sigma(jnp.array([R]), rho_s, r_s, c)[0])
                np.testing.assert_allclose(ana, num, rtol=3e-3)

    def test_uk_alias(self):
        assert tnfw_uk is nfw_uk_jax

    def test_grads_finite_at_branch_points(self):
        c = 6.0
        xs = jnp.array([0.5, 0.99, 0.9999, 1.0, 1.0001, 1.01, 2.0,
                        5.999, 6.0, 6.001, 10.0])
        for fn in (tnfw_sigma, tnfw_mean_sigma):
            g = jax.vmap(jax.grad(
                lambda x: fn(jnp.array([x]), 1e6, 1.0, c)[0]))(xs)
            assert bool(jnp.all(jnp.isfinite(g))), fn.__name__
        gc = jax.vmap(lambda x: jax.grad(
            lambda cc: tnfw_sigma(jnp.array([x]), 1e6, 1.0, cc)[0])(c))(xs)
        assert bool(jnp.all(jnp.isfinite(gc)))


class TestBMO:
    def test_kernel_goldens(self):
        with enable_x64():
            f = np.asarray(_bmo_sigma_dl(jnp.asarray(GOLD_X), 12.5))
            g = np.asarray(_bmo_bsigma_dl(jnp.asarray(GOLD_X), 12.5))
            m = np.asarray(_m_bmo_dl(jnp.asarray(GOLD_X), 12.5))
        np.testing.assert_allclose(f, BMO_SIGMA_T12P5, rtol=1e-7)
        np.testing.assert_allclose(g, BMO_BSIGMA_T12P5, rtol=1e-7)
        np.testing.assert_allclose(m, BMO_MASS_T12P5, rtol=1e-7)

    @pytest.mark.parametrize("tau", [3.0, 12.5, 25.0])
    def test_mass_total_golden(self, tau):
        with enable_x64():
            np.testing.assert_allclose(float(_m_bmo_tot_dl(jnp.asarray(tau))),
                                       BMO_MTOT[tau], rtol=1e-10)

    def test_nfw_limit_large_tau(self):
        with enable_x64():
            R = jnp.logspace(-2, 0.5, 20)
            s_b = np.asarray(bmo_sigma(R, 1.4e15, 0.2, 1e4))
            s_n = np.asarray(nfw_sigma(R, 1.4e15, 0.2))
            np.testing.assert_allclose(s_b, s_n, rtol=1e-3)
            d_b = np.asarray(bmo_delta_sigma(R, 1.4e15, 0.2, 1e4))
            d_n = np.asarray(nfw_delta_sigma(R, 1.4e15, 0.2))
            np.testing.assert_allclose(d_b, d_n, rtol=2e-3)

    def test_abel_projection(self):
        from scipy.integrate import quad
        with enable_x64():
            rho_s, r_s, tau = 1.4e15, 0.2, 12.5
            for R in (0.05, 0.5, 3.0):
                num = 2.0 * quad(
                    lambda zz: float(bmo_rho(
                        jnp.array([np.sqrt(R**2 + zz**2)]), rho_s, r_s, tau)[0]),
                    0.0, np.inf, limit=400)[0]
                ana = float(bmo_sigma(jnp.array([R]), rho_s, r_s, tau)[0])
                np.testing.assert_allclose(ana, num, rtol=3e-3)

    def test_mass_conservation_2d(self):
        with enable_x64():
            rho_s, r_s, tau = 1.4e15, 0.2, 12.5
            R_big = 3000.0
            m2d = (np.pi * R_big**2
                   * float(bmo_mean_sigma(jnp.array([R_big]), rho_s, r_s, tau)[0]))
            m_tot = float(bmo_mass_total(rho_s, r_s, tau))
            # Σ̄ converges to M_tot/(πR²) only logarithmically slowly (ρ ∝ r⁻⁷)
            np.testing.assert_allclose(m2d, m_tot, rtol=5e-3)
            m3d = float(bmo_mass(jnp.array([1e5 * r_s]), rho_s, r_s, tau)[0])
            np.testing.assert_allclose(m3d, m_tot, rtol=1e-6)

    def test_uk_goldens(self):
        with enable_x64():
            uk = np.asarray(bmo_uk_jax(jnp.asarray(BMO_UK_K / 0.2),
                                       jnp.array([0.2]), jnp.array([15.0])))[:, 0]
        np.testing.assert_allclose(uk, BMO_UK_T15P0, rtol=5e-5)

    def test_uk_low_k_guard(self):
        uk = bmo_uk_jax(jnp.array([1e-7]), jnp.array([0.2]), jnp.array([15.0]))
        np.testing.assert_allclose(float(uk[0, 0]), 1.0)

    def test_grads_finite(self):
        xs = jnp.array([0.005, 0.5, 0.99, 1.0, 1.01, 2.0, 12.5, 40.0])
        for fn in (bmo_sigma, bmo_mean_sigma):
            g = jax.vmap(jax.grad(
                lambda x: fn(jnp.array([x]), 1e6, 1.0, 12.5)[0]))(xs)
            assert bool(jnp.all(jnp.isfinite(g))), fn.__name__
        gt = jax.grad(lambda t: bmo_uk_jax(jnp.array([1.0, 1e-6]),
                                           jnp.array([0.2]),
                                           jnp.array([t])).sum())(15.0)
        assert bool(jnp.isfinite(gt))


class TestHernquist:
    def test_kernel_goldens(self):
        with enable_x64():
            f = np.asarray(_hern_sigma_dl(jnp.asarray(GOLD_X)))
            g = np.asarray(_hern_bsigma_dl(jnp.asarray(GOLD_X)))
        np.testing.assert_allclose(f, HERN_SIGMA, rtol=1e-7)
        np.testing.assert_allclose(g, HERN_BSIGMA, rtol=1e-7)

    def test_enclosed_mass_identity(self):
        m_tot, r_b = 3e11, 0.005
        r = jnp.array([0.001, 0.005, 0.05, 5.0])
        m = np.asarray(hernquist_mass(r, m_tot, r_b))
        x = np.asarray(r) / r_b
        np.testing.assert_allclose(m, m_tot * x**2 / (1 + x)**2, rtol=1e-6)

    def test_2d_mass_convergence(self):
        with enable_x64():
            m_tot, r_b = 3e11, 0.005
            R = 5.0  # x = 1000
            m2d = np.pi * R**2 * float(
                hernquist_mean_sigma(jnp.array([R]), m_tot, r_b)[0])
            np.testing.assert_allclose(m2d, m_tot, rtol=3e-3)

    def test_abel_projection(self):
        from scipy.integrate import quad
        with enable_x64():
            m_tot, r_b = 3e11, 0.005
            for R in (0.002, 0.005, 0.05):
                num = 2.0 * quad(
                    lambda zz: float(hernquist_rho(
                        jnp.array([np.sqrt(R**2 + zz**2)]), m_tot, r_b)[0]),
                    0.0, np.inf, limit=400)[0]
                ana = float(hernquist_sigma(jnp.array([R]), m_tot, r_b)[0])
                np.testing.assert_allclose(ana, num, rtol=3e-3)

    def test_delta_sigma_identity(self):
        R = jnp.logspace(-3, 0, 30)
        ds = hernquist_delta_sigma(R, 3e11, 0.005)
        expect = (hernquist_mean_sigma(R, 3e11, 0.005)
                  - hernquist_sigma(R, 3e11, 0.005))
        np.testing.assert_allclose(np.asarray(ds), np.asarray(expect),
                                   rtol=1e-5)

    def test_grads_finite(self):
        xs = jnp.array([0.01, 0.5, 0.99, 1.0, 1.01, 2.0, 100.0])
        for fn in (hernquist_sigma, hernquist_mean_sigma):
            g = jax.vmap(jax.grad(
                lambda x: fn(jnp.array([x]), 1e12, 1.0)[0]))(xs)
            assert bool(jnp.all(jnp.isfinite(g))), fn.__name__


class TestNfwParamsFromMass:
    def test_matches_haloprofile(self, planck_cosmo):
        # regression on the mdef_delta_rho extraction: bit-compatible with
        # HaloProfile.rho_s_and_rs for the JAX-native dutton14/200c path
        hp = HaloProfile({}, cm_relation="dutton14", mdef="200c")
        m = jnp.array([1e13, 1e14, 1e15])
        z = 0.4
        rho_hp, rs_hp = hp.rho_s_and_rs(m, z, planck_cosmo)
        c = hp.concentration(m, z)
        rho_f, rs_f, r_delta = nfw_params_from_mass(m, c, z, planck_cosmo,
                                                    "200c")
        np.testing.assert_allclose(np.asarray(rho_f), np.asarray(rho_hp),
                                   rtol=1e-7)
        np.testing.assert_allclose(np.asarray(rs_f), np.asarray(rs_hp),
                                   rtol=1e-7)
        np.testing.assert_allclose(np.asarray(r_delta),
                                   np.asarray(rs_f) * np.asarray(c), rtol=1e-6)

    @pytest.mark.parametrize("mdef", ["200m", "200c", "vir"])
    def test_mass_definition_closure(self, mdef, planck_cosmo):
        # sphere consistency: M = (4/3)π delta rho_ref r_delta³
        delta, rho_ref = mdef_delta_rho(mdef, 0.4, planck_cosmo)
        m = jnp.array([3e14])
        _, _, r_delta = nfw_params_from_mass(m, jnp.array([5.0]), 0.4,
                                             planck_cosmo, mdef)
        m_sphere = (4.0 / 3.0) * np.pi * delta * rho_ref * float(r_delta[0])**3
        np.testing.assert_allclose(m_sphere, 3e14, rtol=1e-5)
