"""One-off golden-value generator for tests/test_lensing_profiles.py and
tests/test_lensing_observables.py.

Prints paste-ready python dicts of reference values for the truncated-NFW /
BMO / Hernquist lensing kernels, the P/Q hyperbolic-integral combinations
(mpmath, 50 digits), the BMO Fourier window (reference formula with exact
scipy/mpmath special functions) and Σ_crit (reference halo_lensing formula on
colossus planck18).

Dev-only: colossus / mpmath / the halo_lensing clone are allowed HERE and
nowhere in the package.

Usage
-----
python hod_mod/scripts/cosmology/make_lensing_goldens.py \
    --halo-lensing-path /path/to/halo_lensing/clone
"""

import argparse
import sys

import numpy as np


def _fmt(arr):
    return "np.array(" + np.array2string(
        np.asarray(arr, dtype=np.float64), separator=", ",
        formatter={"float_kind": lambda v: f"{v:.12e}"},
        threshold=10_000, max_line_width=88,
    ) + ")"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--halo-lensing-path", required=True,
                    help="path to a clone of github.com/massarin/halo_lensing")
    args = ap.parse_args()
    sys.path.insert(0, args.halo_lensing_path)

    import mpmath as mp
    import halo_lensing as ref
    from colossus.cosmology import cosmology as col
    from scipy.special import sici

    cosmo = col.setCosmology("planck18")
    mp.mp.dps = 50

    print("# Generated by hod_mod/scripts/cosmology/make_lensing_goldens.py")
    print("# (reference: massarin/halo_lensing @ colossus planck18; mpmath dps=50)")
    print("import numpy as np\n")

    # ---- kernel grids ------------------------------------------------------
    x = np.array([1e-3, 0.01, 0.1, 0.3, 0.5, 0.9, 0.985, 1.0, 1.015, 1.5,
                  2.0, 2.9, 3.0, 5.0, 6.0, 8.0, 15.0, 40.0])
    print("GOLD_X =", _fmt(x))

    # TJ dimensionless kernels (reference coded forms == hod_mod kernels;
    # hod_mod multiplies by 4 rho_s r_s — physical normalization, see
    # lensing_profiles module docstring)
    for c in (3.0, 6.0, 15.0):
        print(f"TJ_SIGMA_C{int(c)} =", _fmt(ref.tj_sigma_dl(x, c)))
        print(f"TJ_BSIGMA_C{int(c)} =", _fmt(ref.tj_bsigma_dl(x, c)))

    # BMO dimensionless kernels + masses
    for tau in (3.0, 12.5, 25.0):
        tag = str(tau).replace(".", "P")
        print(f"BMO_SIGMA_T{tag} =", _fmt(ref.bmo_sigma_dl(x, tau)))
        print(f"BMO_BSIGMA_T{tag} =", _fmt(ref.bmo_bsigma_dl(x, tau)))
        print(f"BMO_MASS_T{tag} =", _fmt(ref.m_bmo(x, tau)))
        print(f"BMO_MTOT_T{tag} = {ref.m_bmo_tot(tau):.12e}")

    # Hernquist dimensionless kernels
    print("HERN_SIGMA =", _fmt(ref.hern_sigma_dl(x)))
    print("HERN_BSIGMA =", _fmt(ref.hern_bsigma_dl(x)))

    # ---- P/Q hyperbolic combinations via mpmath (scaled, exact) ------------
    xpq = np.array([1e-3, 0.1, 0.5, 2.0, 13.9, 14.1, 29.0, 31.0, 50.0, 300.0])
    p_mp, q_mp = [], []
    for xv in xpq:
        # P = −[eˣE1 + e⁻ˣEi]/2, Q = [e⁻ˣEi − eˣE1]/2 — no overflow at dps=50
        e1s = mp.exp(xv) * mp.e1(xv)
        eis = mp.exp(-xv) * mp.ei(xv)
        p_mp.append(float(-(e1s + eis) / 2))
        q_mp.append(float((eis - e1s) / 2))
    print("PQ_X =", _fmt(xpq))
    print("P_GOLD =", _fmt(p_mp))
    print("Q_GOLD =", _fmt(q_mp))

    # ---- BMO Fourier window: reference formula with exact special fns ------
    # y_bmo with mpmath P/Q and scipy sici, renormalized to the total BMO
    # mass (hod_mod convention u(k→0) = 1).
    K = np.logspace(-3, 2.5, 23)
    for tau in (7.5, 15.0):
        tag = str(tau).replace(".", "P")
        si, ci = sici(K)
        p = np.empty_like(K)
        q = np.empty_like(K)
        for i, kv in enumerate(K):
            e1s = mp.exp(tau * kv) * mp.e1(tau * kv)
            eis = mp.exp(-tau * kv) * mp.ei(tau * kv)
            p[i] = float(-(e1s + eis) / 2)
            q[i] = float((eis - e1s) / 2)
        t = tau
        f1 = t / (4.0 * ref.m_bmo_tot(t) * (1.0 + t**2) ** 3 * K)
        f2 = (2.0 * (3.0 * t**4 - 6.0 * t**2 - 1.0) * p
              - 2.0 * t * (t**4 - 1.0) * K * q
              - 2.0 * t**2 * np.pi * np.exp(-t * K) * ((t**2 + 1.0) * K + 4.0 * t)
              + 2.0 * t**3 * (np.pi - 2.0 * si)
              * (4.0 * np.cos(K) + (t**2 + 1.0) * K * np.sin(K))
              + 4.0 * t**3 * ci * (4.0 * np.sin(K) - (t**2 + 1.0) * K * np.cos(K)))
        print(f"BMO_UK_K = ", _fmt(K)) if tau == 7.5 else None
        print(f"BMO_UK_T{tag} =", _fmt(f1 * f2))

    # ---- Sigma_crit (reference formula, colossus planck18) -----------------
    zl = np.array([0.2, 0.3, 0.5])
    zs = np.array([0.8, 1.0, 2.0, 3.0])
    sc = np.array([[ref.sigma_crit(a, b, cosmo, comoving=True)
                    for b in zs] for a in zl])
    print("SC_ZL =", _fmt(zl))
    print("SC_ZS =", _fmt(zs))
    print("SIGMA_CRIT_COMOVING =", _fmt(sc))
    print("# colossus planck18: h=%.4f Om0=%.4f Ob0=%.4f ns=%.4f sigma8=%.4f"
          % (cosmo.h, cosmo.Om0, cosmo.Ob0, cosmo.ns, cosmo.sigma8))


if __name__ == "__main__":
    main()
